# First Shot Defense of the Powerplay
    In mixed doubles curling, the powerplay can be played by the team with
the hammer once an end. In the default position, the preplaced stones are
placed with the hammer stone on top of the button, and the non-hammer stone 
as a guard. In the powerplay, both stones are shifted left or right, clearing 
the center line of the board. Teams with the hammer or the last stone 
advantage typically win the end in regular and power play ends. However, 
in regular ends, analysts have observed that mixed doubles is a game focused 
on execution. With the positioning of the preplaced stones, most of the 
non-hammer team's success is determined by how well they execute their 
first shot, usually a draw around the center guard, where the stone is 
delivered to rest behind the guard. In the powerplay, there is much more 
variety in how the non-hammer team plays the first shot of the end. Some 
common shots include a draw around the guard and a tick shot, which is 
intended to move the hammer team's guard stone while keeping the 
shooter's stone in play.
    While analysts note teams use various shots to counter the power play, 
there is little literature on power play strategies or outcomes. Thus, it is 
important to compare how board positions and shot types affect metrics such 
as non-hammer win percentage and points. Also, determining contexts in which 
teams use different shots is meaningful. These analyses confirm and expand 
analyst observations. The purpose of this section is to identify and analyze 
first shots against the power play and the scenarios in which teams choose 
specific plays. 

# Methods/Data


# Results


# Discussion