---
title: "Defensive Risk and Reward in Curling Proposal"
author: "Mark J. Zhang"
date: "2025-10-24"
format:
  pdf:
    colorlinks: true
    linkcolor: blue
    number-sections: true
    geometry: margin=1in
    fontsize: 11pt 
cite-method: citeproc
link-citations: true
suppress-bibliography: false
bibliography: ../references.bib # create your own bib file
csl: apa.csl
---

# Introduction

<!--
Background about your research; touch the three questions to be
addressed in an introduction (why do we care; what have been done;
what's new). 

Cite at least two references. 
Cite a reference in text: @agonafir2022machine did something.
Cite a reference in parenthesis: some interesting work has been done
[@agonafir2022understanding].
-->
Curling, nicknamed "chess on ice", is an official Winter Olympic sport
where two teams take turns sliding stones down a sheet of ice toward
a target known as the house. The team with the hammer-- the privilege of
throwing the final stone in an end-- has the strategic advantage, as they can 
react to the position and attempt to score multiple points.

Previous research has explored how posession of the "hammer" influences 
strategy and win probability. For example, @PARK2013391 find the posession 
of the hammer in the ninth end was more influential in determining the winner
of the game than in other ends. Additionally, an analysis of strategic 
decision shows that at the beginning
of the 10th end, it is preferable to be one point ahead without the
hammer than one point down with the hammer[@doi:10.1287/deca.1050.0032].

In this project, we focus on the defensive strategy in mixed
doubles curling, where the dynamics of play differ substantially from
traditional curling. In particular, we will examine the defense against
the power play, an option unique to mixed doubles that has received little
analytical attention. Understanding how the power play affects the optimal
behavior of the team without the hammer can provide new insights into 
risk-reward tradeoffs and decision-making in modern curling.


# Specific Aims

<!--
Formulate your research question; translate your research questions
into statistical/data science questions.
-->

The primary goal of this project is to analyze risk–reward trade-offs in 
mixed doubles curling, focusing on the decisions faced by the team without
 the hammer. Specifically, we aim to determine under which game states a 
 team should “punt” an end (play conservatively) versus attempt an aggressive
steal.

- How should the team without the hammer adjust its defensive strategy in 
  response to the opponent’s use of the power play to maximize expected win
   probability in mixed doubles curling?

## Supporting Questions

- How does the power play affect the probability that the team without the
  hammer successfully steals an end under different score differentials 
  and end numbers?
- How does defensive response to the power play change the probability 
  of giving up multiple points in the end?
- Can we identify score differentials, end numbers, or stone placement 
  scenarios where the team without the hammer should switch from a
  conservative to aggressive defensive strategy in response to a power play?

# Data

<!--
You should have identified the data needed for your project, instead
of stating that you will try to find some data. Give a description
about your data (source, coverage, key variables, structure, etc.) 
and justify its suitability for your research questions.
-->

The data for this project are provided by Curlit, an information technology 
company specializing in curling analytics. Shot-by-shot stone positions are 
available for the Beijing 2022 Olympic Winter Games and the World Mixed Doubles 
Curling Championships for 2023, 2024, and 2025. The data are stored in six CSV 
files which can be joined using the common identifier, CompetitionID. The primary
files for this research are Ends.csv, Games.csv, and Stones.csv.
The dataset contains over 26,000 observations, each corresponding to a single
stone throw during a match.
Key variables include:

- **Stones.csv**: `EndID`, `Task`, `Points`, and stone positions `Stone_{i}_x`
   and `Stone_{i}_y`.  
  - `Task` indicates the objective of the shot, which can be categorized as 
    aggressive, neutral, or defensive, allowing analysis of the defensive
    team’s playstyle.  
  - `Points` evaluates the execution quality of each shot.  
  - Stone coordinates enable reconstruction of stone placement and strategy
    during each end.  

- **Ends.csv**: `TeamID`, `Result` (points scored), and `PowerPlay` 
  usage (none, left-side, or right-side).  
  - This allows identification of game state, scoring outcomes, and the 
    effect of power plays on defensive strategy.  

- **Games.csv**: `GameID`, `TeamID1`, `TeamID2`, `Winner`, and `LSFE`
   (starting hammer).  
  - Provides overall match outcomes and starting conditions, essential for
    connecting end-level play to match-level win probabilities.  
    
The dataset is suitable for this research because it provides high-resolution, 
shot-by-shot information across multiple top-level competitions. This allows 
for statistical modeling and simulation of defensive strategies in response 
to opponent actions, 
including power plays, and supports the calculation of metrics such as steal
probability, risk of giving up multiple points, and expected win probability.

# Methods and Research Design

<!--
What design or methods will you use? Cite relevant references too if
needed [@agonafir2022machine; @agonafir2022understanding].
Show your thoughts on modeling, visualization, analysis,
prediction, validation, or other methodological issues you need
address in order to answer your scientific questions.
-->

# Discussion

<!--
What are the most challenge parts of the task? What are the
limitations of your work? What is your fall-back plan if something
unexpected happens?
-->

# References  